modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/vi945786/MobHealthIndicators/issues"

[[mods]]
modId = "mobhealthindicators"
version = "${version}"
displayName = "Mob Health Indicators"
description = '''Displays a health bar above mobs'''
authors = "vi945786"
logoFile = "assets/mobhealthindicators/icon.png"
displayURL = "https://modrinth.com/mod/mob-health-indicators"
modUrl = "https://github.com/vi945786/MobHealthIndicators"

[[mixins]]
config = "mobhealthindicators.mixins.json"

[[dependencies.mobhealthindicators]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mobhealthindicators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mobhealthindicators]]
modId = "cloth_config"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"
